### ISSUE TITLE
DefenseFinder update fails with the new release

### ISSUE THREAD

**Issue by eloilit** [mdmparis/defense-finder#16]
Hello,
I'm having troubles installing DefenseFinder with the recent release of models.

I've built a new conda environment and installed DefenseFinder from scratch.
Everything is fine until the command "defense-finder update" is typed. It yields the following error message :

![image](https://user-images.githubusercontent.com/34735700/193575789-8c21e3b6-3cb8-49e6-88cf-b224c19fa7af.png)

Thanks in advance,

Eloi

**Comment by eloilit** [comment]
The problem looks very similar to the one described here:
https://github.com/gem-pasteur/macsyfinder/issues/50#issuecomment-1183786551

**Comment by eloilit** [comment]
Works well, thanks ! 
Didn't notice this issue ;)

**Comment by JhonPhage** [comment]
> Hi, Have you tried this #8 ? [https://github.com/mdmparis/defense-finder/issues/8](url) `sudo macsydata install -U -u --org mdmparis defense-finder-models`
> 
> It works for me to update after the same issue. But now I have to deal with issue #5 ... => OK with "sudo"
> 
> Guillaume

Thank you very much! It works for me too.

**Comment by yayaHu** [comment]
> Hi, Have you tried this #8 ? [https://github.com/mdmparis/defense-finder/issues/8](url) `sudo macsydata install -U -u --org mdmparis defense-finder-models`
> 
> It works for me to update after the same issue. But now I have to deal with issue #5 ... => OK with "sudo"
> 
> Guillaume

**Comment by yayaHu** [comment]
> Hi, Have you tried this #8 ? [https://github.com/mdmparis/defense-finder/issues/8](url) `sudo macsydata install -U -u --org mdmparis defense-finder-models`
> 
> It works for me to update after the same issue. But now I have to deal with issue #5 ... => OK with "sudo"
> 
> Guillaume

Works well for me too, Thx!
