### ISSUE TITLE
defense-finder update error: IndexError: list index out of range | issue downloading models

### ISSUE THREAD

**Issue by scubalaina** [mdmparis/defense-finder#23]
Hi there!
Very excited to use defense-finder - but there appears to be some errors in retrieving the models to run defense-finder.

I began installing defense-finder with pip after creating an environment.

(Also, by the way, the conda environment creation command written on the page has the flag '-name', but should be '-n' or '--name'. Probably just a typo from the author, but it causes an error when the copy-pasting the installation code.)

Here is the installation commands I used:
```
conda create -n defensefinder
conda activate defensefinder
pip install mdmparis-defense-finder
defense-finder update
```
I receive the following error:
```
Downloading defense-finder-models (1.2.2).
Extracting defense-finder-models (1.2.2).
Removing old models /tmp/tmp-macsy-cache/mdmparis/defense-finder-models/1.2.2/defense-finder-models
Traceback (most recent call last):
  File "/home/aweinheimer/miniconda3/bin/macsydata", line 8, in <module>
    sys.exit(main())
  File "/home/aweinheimer/miniconda3/lib/python3.10/site-packages/macsypy/scripts/macsydata.py", line 938, in main
    parsed_args.func(parsed_args)
  File "/home/aweinheimer/miniconda3/lib/python3.10/site-packages/macsypy/scripts/macsydata.py", line 348, in do_install
    dest = config.models_dir()[0]
IndexError: list index out of range

```

When I look in the folder `/tmp/tmp-macsy-cache/mdmparis/defense-finder-models/1.2.2/defense-finder-models` , things have downloaded there, but not the `defense-finder-models/DefenseFinder_1`, ` defense-finder-models/DefenseFinder_2`, etc. files used for the defense-finder command (eg: /home/aweinheimer/miniconda3/bin/macsyfinder --db-type ordered_replicon --sequence-db data/gorg_dark/AG-538-A01_contigs/annotation_AG-538-A01_contigs/prokka_AG-538-A01_contigs/AG-538-A01_contigs.faa **--models defense-finder-models/DefenseFinder_2** all --out-dir /mnt/scgc/stepanauskas_nfs/aweinheimer/test_def/defense-finder-tmp/DF_2 --coverage-profile 0.1 --w 0 --exchangeable-weight 1).

I tried downloading the models directly with gitclone:
```
git clone https://github.com/mdmparis/defense-finder-models.
```
And it looks like the same files are in that folder, but still no DefenseFinder_1, DefenseFinder_2, etc that are needed to run the command.

Please let me know how I can download the correct models to run defense-finder, since those provided on github appear to be outdated/error-prone or something.

Thank you!

**Comment by genomicsgroup** [comment]
@scubalaina 
Hi~
I have the similar error to you, but i tryed a different install command solved this problem. when using 'defensefinder' conda env, I use the ‘sudo’ to install defence-finder
`sudo pip install mdmparis-defense-finder`
And running with the command 
`defense-finder update --models-dir XXX`
the update process will complete successfully, and you will have these output:
Downloading defense-finder-models (1.2.2).
Extracting defense-finder-models (1.2.2).
Installing defense-finder-models (1.2.2) in /data/defence-finder-models/
Cleaning.
The models defense-finder-models (1.2.2) have been installed successfully.

**Comment by adriangeerre** [comment]
Hi, sorry to intrude, I am having the same issue but I cannot use pip to install defense-finder. Has someone found a work around?

Thanks!

**Comment by adriangeerre** [comment]
Hi again,

I have solved my issue by download the models from github and using the argument _--models-dir_ when executing _defense-finder run_.  I include the cloned directory inside an empty folder. When the model directory was in a folder together with other folders, defense-finder would look for profiles in other folders (in my case hidden folders) showing the error:

```
command used: DefenseFinder/bin/macsyfinder --db-type ordered_replicon --sequence-db annotation/annot.faa --models defense-finder-models/DefenseFinder_1 all --out-dir TEST/defense-finder-tmp/DF_1 --coverage-profile 0.1 --w 4 --exchangeable-weight 1 --models-dir defense-finder-models
Traceback (most recent call last):
  File "DefenseFinder/bin/macsyfinder", line 8, in <module>
    sys.exit(main())
  File "DefenseFinder/lib/python3.10/site-packages/macsypy/scripts/macsyfinder.py", line 1045, in main
    models_loc_available = scan_models_dir(model_dir,
  File "DefenseFinder/lib/python3.10/site-packages/macsypy/registries.py", line 74, in scan_models_dir
    new_model = ModelLocation(path=model_path,
  File "DefenseFinder/lib/python3.10/site-packages/macsypy/registries.py", line 174, in __init__
    self._profiles = self._scan_profiles(profile_dir,
  File "DefenseFinder/lib/python3.10/site-packages/macsypy/registries.py", line 249, in _scan_profiles
    for profile in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: 'defense-finder-models/.git/profiles'
```
Thus, @scubalaina, **I would suggest that there is a bug in the folder indexing** of the script _registries.py_ where the hidden folders (e.g., .git, .pgap, etc) should be avoided.

Thanks for a nice tool!

**Comment by davidmadariaga** [comment]
Hi, hope you are doing great. what those "XXX" mean in this command: "defense-finder update --models-dir **XXX**"

Thanks in advance,

greetings from chile!

> @scubalaina Hi~ I have the similar error to you, but i tryed a different install command solved this problem. when using 'defensefinder' conda env, I use the ‘sudo’ to install defence-finder `sudo pip install mdmparis-defense-finder` And running with the command `defense-finder update --models-dir XXX` the update process will complete successfully, and you will have these output: Downloading defense-finder-models (1.2.2). Extracting defense-finder-models (1.2.2). Installing defense-finder-models (1.2.2) in /data/defence-finder-models/ Cleaning. The models defense-finder-models (1.2.2) have been installed successfully.
