### ISSUE TITLE
request: add defense-finder to bioconda

### ISSUE THREAD

**Issue by alexweisberg** [mdmparis/defense-finder#25]
Hi, Defense-finder is fantastic and a really useful tool for my research. Thank you for developing it.

I was wondering if it could be added to bioconda so that it can be included in other bioconda recipes as a dependency? Similar to how macsyfinder is in bioconda? 

Thank you!

**Comment by jeanrjc** [comment]
Hi @alexweisberg 

DefenseFinder is already on bioconda (https://anaconda.org/bioconda/defense-finder/)

Best

**Comment by alexweisberg** [comment]
Thank you!
