### ISSUE TITLE
Something wrong when I run until “Computing best solutions for UserReplicon ”

### ISSUE THREAD

**Issue by gjzheng** [mdmparis/defense-finder#26]
the log：
######### Hits analysis for replicon UserReplicon ##########[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Aditi/Aditi[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/BREX/BREX[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/BREX/BREX_I[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/BREX/BREX_II[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/BREX/BREX_III[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/BREX/BREX_IV[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/BREX/BREX_V[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/BREX/BREX_VI[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Borvo/Borvo[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Bunzi/Bunzi[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/CBASS/CBASS[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/CBASS/CBASS_I[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/CBASS/CBASS_II[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/CBASS/CBASS_III[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/CBASS/CBASS_IV[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Dazbog/Dazbog[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Eleos/Eleos[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Olokun/Olokun[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/PfiAT/PfiAT[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Pycsar/Pycsar[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Retron/Retron_II[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Retron/Retron_III[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Retron/Retron_IV[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Retron/Retron_IX[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Retron/Retron_I_A[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Retron/Retron_I_B[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Retron/Retron_I_C[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Retron/Retron_V[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Retron/Retron_VI[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Retron/Retron_VIII[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Retron/Retron_VII_1[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Retron/Retron_VII_2[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Retron/Retron_X[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Retron/Retron_XI[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Retron/Retron_XII[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Retron/Retron_XIII[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/RnlAB/RnlAB[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/SEFIR/SEFIR[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/SanaTA/SanaTA[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/SoFIC/SoFic[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Tiamat/Tiamat[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/Uzume/Uzume[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32mCheck model defense-finder-models/DefenseFinder_5/pAgo/pAgo[0m
[32mBuilding clusters[0m
[32mSearching systems[0m
[32m
###################### Computing best solutions ######################[0m
[32mComputing best solutions for UserReplicon (nb of candidate systems 240)[0m

**Comment by SenyuanGu** [comment]
Hi, did you figure it out? I came up with the same issue with you... The program stucked in this step for a long time.

**Comment by jsweagley** [comment]
I am just bumping this thread because I have a similar issue with a handful of my files. I am running the current version of defense-finder on .faa protein files generated by Produigal on a cluster, each job has 24 CPUs devoted to it, and they have been running for over 1 day and 14 hours. A majority of the time it has been hung on this step, the last edit to the macsysfinder log files was within 15 minutes of the job starting. 

Looking into the log files, it looks like DF_[1-5] and RM reached the END, only the log in /cas/ is stuck 
An example for one of the run says:

> ###################### Computing best solutions ######################
> INFO     : Computing best solutions for 160-01.meta.genes (nb of candidate systems 80)

For the stuck jobs, it looks like the 'nb of candidate systems' ranges from 76-85. **Does the time to compute the best solution for Cas scale exponentially with the nb of candidate systems?** I didn't record the nb of candidate systems for the runs that finished to determine how this relates to run time. **Is there a --log-level (or  --preserve-raw) parameter setting I could use to store the 'nb of candidate systems' if I rerun these to check the relationship?**
