### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?

### ISSUE THREAD

**Issue by joelwwh** [mdmparis/defense-finder#29]
I am repeatedly getting this error: AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?

Quick search reveals that it's caused by the depracation of "append" in pandas 2.0. Wonder if the code needs an update?

**Comment by jeanrjc** [comment]
Can you give more details about your issue ? (Exact error message, input file, version of soft and models, etc..)
Thanks
