### ISSUE TITLE
Inconsistencies between versions and local VS webserver results.

### ISSUE THREAD

**Issue by TaraBartolec** [mdmparis/defense-finder#38]
Hi Defense-Finder team,

Firstly, thanks for making such a great tool.

I recently updated my defense-finder models to the latest release (v1.2.3) and am getting conflicting results across versions and also on the webserver. The main problem is a missing system (Mokosh Type II) in version 1.2.3 installed locally, that comes up in the old version and also on the current webserver implementation.

Would it be possible to get some help to understand what is going on? Is it an issue of different versions on the webserver implementation? Why would a system disappear across versions?

I have uploaded an example nucleotide fasta and protein fasta (generated by Prodigal defaults). The problem persists no matter which format I start the Defense-Finder analysis in. https://oc.embl.de/index.php/s/VewAdfSzLBd8FHh 
The problem is described in more detail below.

Best,
Tara

The version I installed locally on my computer and ran in March (not sure which version exactly) produced the following systems:
- CAS_Class1-Subtype-I-E
- CAS_Class1-Subtype-I-F
- Gao_Tmn
- PD-T7-4
- Mokosh_TypeII
- Mok_Hok_Sok
- PD-T4-3
- RM_Type_I
- DRT_3

Recent version 1.2.3 run locally produces:
- CAS_Class1-Subtype-I-F
- CAS_Class1-Subtype-I-E
- Gao_Tmn
- Mok_Hok_Sok
- PD-T7-4
- PD-T4-3
- RM_Type_I
- DRT_3
- MazEF
- MazEF
- MazEF

Webserver (I am not sure which version) produces):RM
- RM_Type_I
- Mok_Hok_Sok
- Mokosh_TypeII
- PD-T7-4
- PD-T4-3
- DRT_3
- CAS_Class1-Subtype-I-F
- CAS_Class1-Subtype-I-E
- Gabija
- Gao_Tmn

Mokosh Type II disappears in the newest version of defense-finder. Gabija and MazEF also appear variable.

**Comment by jeanrjc** [comment]
Hello,

We adapted the models and coverage thresholds and newer versions of the models should be the one to keep. It does not mean that older results are wrong, it's just that given our current knowledge, those hits now appear less likely. Depending on your research question you can chose to keep working with them or not. 

The webservice is currently being updated, and should contain the new models and defense finder version with the upcoming release (stay tuned, it will be there : defensefinder.mdmlab.fr, currently redirecting to the old version).
