### ISSUE TITLE
Hmmer execution error

### ISSUE THREAD

**Issue by wentski** [mdmparis/defense-finder#4]
Hi, 
I have managed to install and run defense finder but I am getting the following error when searching for models:

an error occurred during Hmmer execution: command = hmmsearch --cpu 0 -o '/tmp/defense-finder/hmmer_results/csc1gr5_I-D_4.search_hmm.out' --cut_ga '/home/sxtm38/.macsyfinder/data/defense-finder-models/profiles/csc1gr5_I-D_4.hmm' 'defense-finder/sequence.fasta'  : return code = 1 check /tmp/defense-finder/hmmer_results/csc1gr5_I-D_4.search_hmm.err

This error repeats for all models until defence-finder eventually kills the process.

Any suggestions?

Many thanks.

**Comment by the-lagrangian** [comment]
Hi- I had a similar problem, where the underlying error was 
```
/bin/sh: hmmsearch: command not found
```

easily fixed by running `conda install -c bioconda hmmer`

**Comment by jiayue13** [comment]
> Hi, I have managed to install and run defense finder but I am getting the following error when searching for models:
> 
> an error occurred during Hmmer execution: command = hmmsearch --cpu 0 -o '/tmp/defense-finder/hmmer_results/csc1gr5_I-D_4.search_hmm.out' --cut_ga '/home/sxtm38/.macsyfinder/data/defense-finder-models/profiles/csc1gr5_I-D_4.hmm' 'defense-finder/sequence.fasta' : return code = 1 check /tmp/defense-finder/hmmer_results/csc1gr5_I-D_4.search_hmm.err
> 
> This error repeats for all models until defence-finder eventually kills the process.
> 
> Any suggestions?
> 
> Many thanks.

hello, i have the same problem like your question. Did you solve the error: an error occurred during Hmmer execution: command = hmmsearch --cpu 0?
Thanks.
