### ISSUE TITLE
Alignment availability for RefSeq

### ISSUE THREAD

**Issue by Ge0rges** [mdmparis/defense-finder#52]
Hello,

I'm interesting in using your recently produced database on all RefSeq genomes to understand the phylogeny of different viral defense systems. To that end, I was wondering if any alignments have been made using this data (either on all genes, or a subset of system specific genes)? And if not, if this is something that would be of interest.

Thank you.

**Comment by jeanrjc** [comment]
Hello, 

This repo is about the defensefinder software, not particularly about results obtained with it. Beside your question is unclear, but I'm not sure we have what you asked. 

Best
