### ISSUE TITLE
[BUG]Issue with -A Option in DefenseFinder v3.1.0

### ISSUE THREAD

**Issue by maocheng2020** [mdmparis/defense-finder#67]
Hello,

I'm using DefenseFinder, and I believe I have the latest version installed (v3.1.0) (defense-finder update). According to the release notes for v1.3.0, the tool should support the following options:

--antidefense to run AntiDefense models alongside DefenseFinder
--antidefense-only to run only AntiDefense models
However, when I attempt to use the -a or --antidefense-only options in my command, it returns an error stating "No such option: -A". Additionally, when I run defense-finder run -h to check the available options, I do not see any mention of -a or --antidefense.Here is the exact command I used:
defense-finder run vRhyme_955.faa -o test -A

Usage: defense-finder run [OPTIONS] FILE
Try 'defense-finder run -h' for help.
Error: No such option: -A

Could you please help me understand why this option is not being recognized? Is there something I'm missing, or could this be an issue with the current release?

Thank you for your assistance!

**Comment by LemoAlex** [comment]
Dear defense-finder team,

I am running with the same issue as mentioned here. I am trying to run defense-finder from the command line, but the antidefense option is not recognized by the program as I get the same error message as mentioned in the original post. 

I updated the program and tried with different option (-A, --antidefense,--adf ...), but nothing seems to be working. Is this a known issue, or am I doing something wrong ?

Thanks a lot for your time and help !

Alexandre

**Comment by JinwnK** [comment]
I have the same problem, I wonder if DefenseFinder v1.3.0 has updated the annotation for anti immune system-related functions.

**Comment by LemoAlex** [comment]
Hi,

Thanks for the answer. Here is the command:

```
$ defense-finder update --force-reinstall
Downloading defense-finder-models (1.3.0).
Extracting defense-finder-models (1.3.0).
Installing defense-finder-models (1.3.0) in /home/lemopoul/.macsyfinder/models
Cleaning.
The models defense-finder-models (1.3.0) have been installed successfully.
Downloading CasFinder (3.1.0).
Downloading CasFinder (3.1.0).
Extracting CasFinder (3.1.0).
Extracting CasFinder (3.1.0).
Installing CasFinder (3.1.0) in /home/lemopoul/.macsyfinder/models
Installing CasFinder (3.1.0) in /home/lemopoul/.macsyfinder/models
Cleaning.
Cleaning.
The models CasFinder (3.1.0) have been installed successfully.
The models CasFinder (3.1.0) have been installed successfully.


 $ defense-finder version
Usage: defense-finder [OPTIONS] COMMAND [ARGS]...
Try 'defense-finder -h' for help.

Error: No such command 'version'.

```

Thanks,

Alexandre

**Comment by JinwnK** [comment]
> Hello, what's the output of `defense-finder version` ?
> 
> Most likely, you don't have the last version, running version 1.3.0 on my machine works as expected.
> 
> Note that it's possibly the anaconda version that is broken. Install it with pip. (we don't manage the conda version)

I previously updated DefenseFinder, and it showed that the installation was successful.
`$ defense-finder update -f
Downloading defense-finder-models (1.3.0).
Extracting defense-finder-models (1.3.0).
Installing defense-finder-models (1.3.0) in /home/kjw/.macsyfinder/models
Cleaning.
The models defense-finder-models (1.3.0) have been installed successfully.
Downloading CasFinder (3.1.0).
Downloading CasFinder (3.1.0).
Extracting CasFinder (3.1.0).
Extracting CasFinder (3.1.0).
Installing CasFinder (3.1.0) in /home/kjw/.macsyfinder/models
Installing CasFinder (3.1.0) in /home/kjw/.macsyfinder/models
Cleaning.
Cleaning.
The models CasFinder (3.1.0) have been installed successfully.
The models CasFinder (3.1.0) have been installed successfully.`

However, when I just checked the version using pip show, it displayed as follows.
`$ pip show mdmparis-defense-finder
Name: mdmparis-defense-finder
Version: 1.2.2
Summary: Defense Finder: allow for a systematic search of all known anti-phage systems.
Home-page: https://github.com/mdmparis/defense-finder
Author: Jean Cury
Author-email: jean.cury@normalesup.org
License: GPLv3
Location: /public/work/jinwen/software/miniconda3/lib/python3.11/site-packages
Requires: click, colorlog, macsyfinder, pyhmmer, pyrodigal
Required-by:`

**Comment by LemoAlex** [comment]
Hello,

Apparently I had the same problem with the update of the version. I also used `pip install --upgrade mdmparis-defense-finder` and it its now working. I was previously using the conda version, which might explain the failures.

Thanks !

Alexandre
